/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hust.soict.ui.admin;

import edu.hust.soict.dao.DBConnect;
import edu.hust.soict.dao.StudentDAO;
import edu.hust.soict.logic.CheckManagerStudent;
import edu.hust.soict.objects.Student;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// [873, 465]

/**
 *
 * @author quangnd
 */
public class CreateStudentInfomation extends javax.swing.JPanel {

    private final DefaultTableModel dtmStudent;

    /**
     * Creates new form StudentInfomation
     */
    public CreateStudentInfomation() {
        initComponents();
        dtmStudent = new DefaultTableModel();
        dtmStudent.addColumn("Mã SV");
        dtmStudent.addColumn("Tên sinh viên");
        dtmStudent.addColumn("Ngày sinh");
        dtmStudent.addColumn("Lớp");
        dtmStudent.addColumn("Chương trình ĐT");
        dtmStudent.addColumn("Hệ học");
        dtmStudent.addColumn("Trạng thái");
        dtmStudent.addColumn("Khóa");
        dtmStudent.addColumn("Khoa-Viện");
        dtmStudent.addColumn("Email");
        dtmStudent.addColumn("Đơn vị học phí");
        jTable1.setModel(dtmStudent);
        fetchDataStudent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new java.awt.GridLayout(4, 6));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Mã SV:");
        jPanel3.add(jLabel1);

        jTextField2.setText("\n");
        jPanel3.add(jTextField2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tên sinh viên:");
        jPanel3.add(jLabel3);

        jTextField1.setText("\n");
        jPanel3.add(jTextField1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Email:");
        jPanel3.add(jLabel2);

        jTextField3.setText("\n");
        jPanel3.add(jTextField3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Ngày sinh:");
        jPanel3.add(jLabel4);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(jDateChooser1);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Khóa:");
        jPanel3.add(jLabel5);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020" }));
        jPanel3.add(jComboBox1);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tìm kiếm:");
        jLabel6.setToolTipText("");
        jPanel3.add(jLabel6);

        jComboBox2.setToolTipText("Tìm kiếm sinh viên theo lớp");
        jPanel3.add(jComboBox2);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Đơn vị học phí:");
        jPanel3.add(jLabel7);

        jTextField4.setText("\n");
        jTextField4.setToolTipText("Đơn vị học phí của một tín chỉ");
        jPanel3.add(jTextField4);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Khoa-Viện:");
        jPanel3.add(jLabel8);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Viện CNTT & TT", "Viện ĐTVT", "Viện ĐK & TĐH", "Viện SPKT", "Khoa GDQP", "Khoa GDTC", "Viện TA", "Viện CNTP" }));
        jPanel3.add(jComboBox3);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Hệ học:");
        jPanel3.add(jLabel9);

        jTextField5.setText("\n");
        jTextField5.setToolTipText("Đại học chính quy, Cao đẳng, Văn bằng hai,...");
        jPanel3.add(jTextField5);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Chương trình ĐT:");
        jPanel3.add(jLabel10);

        jTextField7.setText("\n");
        jPanel3.add(jTextField7);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Trạng thái:");
        jPanel3.add(jLabel11);

        jTextField8.setText("\n");
        jTextField8.setToolTipText("Tương ứng với các mức cảnh cáo học tập của sinh viên");
        jPanel3.add(jTextField8);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Lớp:");
        jPanel3.add(jLabel12);

        jTextField9.setText("\n");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField9);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/refresh.png"))); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 30, 27, 180);
        jPanel4.add(jButton4, gridBagConstraints);

        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/add.png"))); // NOI18N
        jButton1.setText("Add New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 173, 27, 0);
        jPanel4.add(jButton1, gridBagConstraints);

        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/bar-chart-reload.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 34, 27, 0);
        jPanel4.add(jButton2, gridBagConstraints);

        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/delete (1).png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 29, 27, 0);
        jPanel4.add(jButton3, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
        jTextField4.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 10).toString());
        jTextField5.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        jTextField7.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        jTextField8.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        jTextField9.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        jDateChooser1.setDate((Date) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
        jComboBox1.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        jComboBox3.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            searchStudentByClass();
        } catch (SQLException ex) {
            Logger.getLogger(CreateStudentInfomation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            StudentDAO stdao = new StudentDAO();
            String ten = jTextField1.getText();
            String masv = jTextField2.getText();
            String email = jTextField3.getText();
            String donviHp = jTextField4.getText();
            Double d = new Double(donviHp);
            String hehoc = jTextField5.getText();
            String ctdt = jTextField7.getText();
            String trangthai = jTextField8.getText();
            Date ngaysinh = jDateChooser1.getDate();
            java.sql.Date sqlDate = new java.sql.Date(ngaysinh.getTime());
            String khoa = (String) jComboBox1.getSelectedItem();
            String department = (String) jComboBox3.getSelectedItem();
            //String lop = (String) jComboBox2.getSelectedItem();
            String lop = jTextField9.getText();
            Student st = new Student(masv, ten, sqlDate, lop, ctdt, hehoc, trangthai, khoa, department, email, d);
            boolean insert = stdao.addNew(st);
            if(insert == true){
                JOptionPane.showMessageDialog(null, "Tạo mới sinh viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            getStudentInfo();
            }else{
            JOptionPane.showMessageDialog(null, "Failed!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(CreateStudentInfomation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(m, "Bạn chưa chọn sinh viên cần xóa!", "Thông báo!", JOptionPane.WARNING_MESSAGE);
        } else {
            int b = JOptionPane.showConfirmDialog(m, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông báo!", JOptionPane.YES_NO_OPTION);
            if (b == JOptionPane.YES_OPTION) {
                try {
                    String maSV = jTextField2.getText();
                    new StudentDAO().deleteStudent(maSV);
                    getStudentInfo();
                } catch (SQLException ex) {
                    Logger.getLogger(CreateStudentInfomation.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        int row = jTable1.getSelectedRow();

        // make sure a row is selected
        if (row < 0) {
            JOptionPane.showMessageDialog(m, "Bạn chưa chọn sinh viên cần thay đổi!", "Thông báo!",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        String ten = jTextField1.getText();
        String masv = jTextField2.getText();
        String email = jTextField3.getText();
        String donVi = jTextField4.getText();
        Double donViDouble = new Double(donVi);
        String hehoc = jTextField5.getText();
        String ctdt = jTextField7.getText();
        String trangThai = jTextField8.getText();
        Date ngaysinh = jDateChooser1.getDate();
        java.sql.Date sqlDate = new java.sql.Date(ngaysinh.getTime());
        String khoa = (String) jComboBox1.getSelectedItem();
        String department = (String) jComboBox3.getSelectedItem();
        //String lop = (String) jComboBox2.getSelectedItem();
        String lop = jTextField9.getText();
        Student st = new Student(masv, ten, sqlDate, lop, ctdt, hehoc, trangThai, khoa, department, email, donViDouble);
        boolean update = new StudentDAO().updateStudent(st);
        if (update == true) {
            JOptionPane.showMessageDialog(m, "Đã cập nhật dữ liệu thành công!", "Thông báo",
                    JOptionPane.INFORMATION_MESSAGE);
            try {
                getStudentInfo();
            } catch (SQLException ex) {
                Logger.getLogger(CreateStudentInfomation.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void fetchDataStudent() {
        PreparedStatement ps = null, ps1 = null;
        ResultSet rs, rs1;
        if (DBConnect.open()) {
            try {
                ps = DBConnect.cnn.prepareStatement("SELECT * FROM thong_tin_sinh_vien");
                rs = ps.executeQuery();
                ps1 = DBConnect.cnn.prepareStatement("SELECT * FROM search");
                rs1 = ps1.executeQuery();
                while (rs1.next()) {
                    jComboBox2.addItem(rs1.getString(1));
                }
                while (jTable1.getRowCount() > 0) {
                    ((DefaultTableModel) jTable1.getModel()).removeRow(0);
                }
                int col = rs.getMetaData().getColumnCount();
                while (rs.next()) {
                    Object[] rows = new Object[col];
                    for (int i = 1; i <= col; i++) {
                        rows[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow() - 1, rows);
                }
                rs.close();
            } catch (SQLException e) {
                Logger.getLogger(Tuition.class.getName()).log(Level.SEVERE, null, e);
            } finally {
                DBConnect.close(ps);
                DBConnect.close(ps1);
            }
        }
    }

    private void searchStudentByClass() throws SQLException {
        String getClass = (String) jComboBox2.getSelectedItem();
        CheckManagerStudent checkManagerStudent = new CheckManagerStudent();
        ResultSet resultSet = checkManagerStudent.getStudentByClass(getClass);
                    while (jTable1.getRowCount() > 0) {
                        ((DefaultTableModel) jTable1.getModel()).removeRow(0);
                    }
                    int col = resultSet.getMetaData().getColumnCount();
                    while (resultSet.next()) {
                        Object[] rows = new Object[col];
                        for (int i = 1; i <= col; i++) {
                            rows[i - 1] = resultSet.getObject(i);
                        }
                        ((DefaultTableModel) jTable1.getModel()).insertRow(resultSet.getRow() - 1, rows);
                    }
    }

    private void getStudentInfo() throws SQLException {
                CheckManagerStudent checkManagerStudent = new CheckManagerStudent();
                ResultSet rs = checkManagerStudent.resetDataStudent();
                while (jTable1.getRowCount() > 0) {
                    ((DefaultTableModel) jTable1.getModel()).removeRow(0);
                }
                int col = rs.getMetaData().getColumnCount();
                while (rs.next()) {
                    Object[] rows = new Object[col];
                    for (int i = 1; i <= col; i++) {
                        rows[i - 1] = rs.getObject(i);
                    }
                    ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow() - 1, rows);
                }
        }
}
