/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hust.soict.ui.admin;

import edu.hust.soict.dao.ClassDAO;
import edu.hust.soict.dao.DBConnect;
import edu.hust.soict.logic.Check;
import edu.hust.soict.logic.CheckCreateCourses;
import edu.hust.soict.objects.MakeCourses;
import edu.hust.soict.util.ExportData;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quangnd
 */
public class CreateCourses extends javax.swing.JPanel {

    private final DefaultTableModel dtmRegister;
    Main main = new Main();

    /**
     * Creates new form StudentInfo
     */
    public CreateCourses() throws SQLException {
        initComponents();
        dtmRegister = new DefaultTableModel();
        dtmRegister.addColumn("Mã lớp");
        dtmRegister.addColumn("Bắt đầu");
        dtmRegister.addColumn("Kết thúc");
        dtmRegister.addColumn("Thứ");
        dtmRegister.addColumn("Tuần học");
        dtmRegister.addColumn("Loại lớp");
        dtmRegister.addColumn("Mã môn học");
        dtmRegister.addColumn("Nhóm");
        dtmRegister.addColumn("Phòng học");
        dtmRegister.addColumn("Học kì");
        dtmRegister.addColumn("Đã ĐK");
        dtmRegister.addColumn("Max ĐK");
        dtmRegister.addColumn("Thời hạn ĐK");
        jTable1.setModel(dtmRegister);
        reSet1();
        reSet2();
        reSet3();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("quan_ly_sinh_vien?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        monHocQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m.idMonHoc FROM MonHoc m");
        monHocList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : monHocQuery.getResultList();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setLayout(new java.awt.GridLayout(4, 6));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Mã lớp* : ");
        jPanel3.add(jLabel1);
        jPanel3.add(jTextField1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Thời hạn ĐK* : ");
        jPanel3.add(jLabel2);

        jDateChooser1.setToolTipText("yyyy-MM-dd Ex:2018-12-31");
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(jDateChooser1);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mã môn học* : ");
        jPanel3.add(jLabel4);
        jPanel3.add(jComboBox1);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Loại lớp* : ");
        jPanel3.add(jLabel5);
        jPanel3.add(jTextField2);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Thứ* : ");
        jPanel3.add(jLabel6);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        jPanel3.add(jComboBox2);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Bắt đầu* : ");
        jPanel3.add(jLabel7);

        jTextField5.setText("HH:mm:ss");
        jTextField5.setToolTipText("HH:mm:ss - Ex: 12:30:00 ");
        jPanel3.add(jTextField5);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Max ĐK* : ");
        jPanel3.add(jLabel8);
        jPanel3.add(jTextField4);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tuần học* : ");
        jPanel3.add(jLabel9);
        jPanel3.add(jTextField3);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Kết thúc* : ");
        jPanel3.add(jLabel10);

        jTextField7.setText("HH:mm:ss");
        jTextField7.setToolTipText("HH:mm:ss - Ex: 15:30:00 ");
        jPanel3.add(jTextField7);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Phòng học* : ");
        jPanel3.add(jLabel11);
        jPanel3.add(jTextField6);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nhóm* : ");
        jPanel3.add(jLabel3);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TC" }));
        jComboBox4.setSelectedIndex(-1);
        jPanel3.add(jComboBox4);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Học kì* : ");
        jPanel3.add(jLabel12);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20181", "20182", "20183", "20191", "20192", "20193", "20201", "20202", "20203", "20211", "20212", "20213", "20221", "20222", "20223", "20231", "20232", "20233", "20241", "20242", "20243", "20251", "20252", "20253" }));
        jPanel3.add(jComboBox3);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/add.png"))); // NOI18N
        jButton1.setText("Add new");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 184, 0, 0);
        jPanel4.add(jButton1, gridBagConstraints);

        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/refresh.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 86, 0, 0);
        jPanel4.add(jButton2, gridBagConstraints);

        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/delete (1).png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 184, 1, 0);
        jPanel4.add(jButton3, gridBagConstraints);

        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/bar-chart-reload.png"))); // NOI18N
        jButton4.setText("Reset");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 86, 1, 0);
        jPanel4.add(jButton4, gridBagConstraints);

        jButton5.setForeground(new java.awt.Color(204, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/fileexport.png"))); // NOI18N
        jButton5.setText("Export");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 67, 0, 136);
        jPanel4.add(jButton5, gridBagConstraints);

        jButton6.setForeground(new java.awt.Color(204, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/cloud-computing.png"))); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 67, 1, 136);
        jPanel4.add(jButton6, gridBagConstraints);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CheckCreateCourses checkCreateCourses = new CheckCreateCourses();
        String maLop = jTextField1.getText();
        String loaiLop = jTextField2.getText();
        String string = jTextField4.getText();
        int maxDK = Integer.parseInt(string);
        String phongHoc = jTextField6.getText();
        java.util.Date hanDK = jDateChooser1.getDate();
        java.sql.Date sqlDate = new java.sql.Date(hanDK.getTime());
        String thu = (String) jComboBox2.getSelectedItem();
        String tuanHoc = jTextField3.getText();
        String nhom = (String) jComboBox4.getSelectedItem();
        String maMonHoc = (String) jComboBox1.getSelectedItem();
        String batDau = jTextField5.getText();
        String ketThuc = jTextField7.getText();
        String hocki = (String) jComboBox3.getSelectedItem();
        MakeCourses makeCourses = new MakeCourses(maLop, batDau, ketThuc, thu, tuanHoc, loaiLop, maMonHoc, nhom, phongHoc, maxDK, hocki, sqlDate);
        boolean resultCheck = checkCreateCourses.checkManagerCourse(makeCourses);
        if(resultCheck == true){
            try {
                JOptionPane.showMessageDialog(this.main, "Thêm mới thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                reSet3();
            } catch (SQLException ex) {
                Logger.getLogger(CreateCourses.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
         JOptionPane.showMessageDialog(this.main, "Dữ liệu nhập sai hãy nhập lại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CheckCreateCourses checkCreateCourses = new CheckCreateCourses();
//        boolean check = checkCreateCourses.checkSelectedRow();
//        if (check == false) {
//            JOptionPane.showMessageDialog(this.main, "Bạn chưa chọn Lớp cần thay đổi!", "Thông báo!",
//                    JOptionPane.WARNING_MESSAGE);
//            return;
//        }
        int row = jTable1.getSelectedRow();
        // make sure a row is selected
        if (row < 0) {
            JOptionPane.showMessageDialog(this.main, "Bạn chưa chọn lớp cần thay đổi!", "Thông báo!",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        String maLop = jTextField1.getText();
        String loaiLop = jTextField2.getText();
        String string = jTextField4.getText();
        int maxDK = Integer.parseInt(string);
        String phongHoc = jTextField6.getText();
        java.util.Date hanDK = jDateChooser1.getDate();
        java.sql.Date sqlDate = new java.sql.Date(hanDK.getTime());
        String thu = (String) jComboBox2.getSelectedItem();
        String tuanHoc = jTextField3.getText();
        String nhom = (String) jComboBox4.getSelectedItem();
        String maMonHoc = (String) jComboBox1.getSelectedItem();
        String batDau = jTextField5.getText();
        String ketThuc = jTextField7.getText();
        String hocki = (String) jComboBox3.getSelectedItem();
        MakeCourses updateCourses = new MakeCourses(maLop, batDau, ketThuc, thu, tuanHoc, loaiLop, maMonHoc, nhom, phongHoc, maxDK, hocki, sqlDate);
        boolean checkUpdate = checkCreateCourses.checkUpdateCourses(updateCourses);
        if(checkUpdate == false){
        JOptionPane.showMessageDialog(this.main, "Dữ liệu nhập sai hãy nhập lại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this.main, "Đã cập nhật dữ liệu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            try {
                reSet3();
            } catch (SQLException ex) {
                Logger.getLogger(CreateCourses.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this.main, "Bạn chưa chọn lớp cần xóa!", "Thông báo!", JOptionPane.WARNING_MESSAGE);
        } else {
            int b = JOptionPane.showConfirmDialog(this.main, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông báo!", JOptionPane.YES_NO_OPTION);
            if (b == JOptionPane.YES_OPTION) {
                String malop = jTextField1.getText();
                boolean check = new CheckCreateCourses().deleteCourses(malop);
                if(check == true){
                    try {
                        JOptionPane.showMessageDialog(this.main, "Đã xóa thành công mã lớp!" + malop, "Thông báo!", JOptionPane.INFORMATION_MESSAGE);
                        reSet3();
                    } catch (SQLException ex) {
                        Logger.getLogger(CreateCourses.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                JOptionPane.showMessageDialog(this.main, "Đã co loi xay ra!" + malop, "Thông báo!", JOptionPane.ERROR_MESSAGE);
                }
                //new CheckCreateCourses().reSet();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CheckCreateCourses checkCreateCourses = new CheckCreateCourses();
        //checkCreateCourses.reSet();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ExportData export = new ExportData();
        export.exportExcel(jTable1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            searchCoursesByClass();
        } catch (SQLException ex) {
            Logger.getLogger(CreateCourses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        jTextField4.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString());
        jTextField6.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
        jTextField5.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        jTextField7.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        jComboBox1.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        jComboBox2.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        jComboBox3.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
        jComboBox4.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        jDateChooser1.setDate((Date) jTable1.getValueAt(jTable1.getSelectedRow(), 12));
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JComboBox<String> jComboBox3;
    public javax.swing.JComboBox<String> jComboBox4;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    private java.util.List<edu.hust.soict.objects.MonHoc> monHocList;
    private javax.persistence.Query monHocQuery;
    // End of variables declaration//GEN-END:variables

    private void searchCoursesByClass() throws SQLException {
        String group = (String) jComboBox4.getSelectedItem();
        CheckCreateCourses checkCreateCourses = new CheckCreateCourses();
        ResultSet resultSet = checkCreateCourses.getDataFromSearchFunction(group);
            while (jTable1.getRowCount() > 0) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            }
                int col = resultSet.getMetaData().getColumnCount();
            while (resultSet.next()) {
                Object[] rows = new Object[col];
                for (int i = 1; i <= col; i++) {
                    rows[i - 1] = resultSet.getObject(i);
                }
                   ((DefaultTableModel) jTable1.getModel()).insertRow(resultSet.getRow() - 1, rows);
            }
    }

//    private void reSet2() {
//        jTextField1.setText("");
//        jTextField2.setText("");
//        jTextField4.setText("");
//        jTextField6.setText("");
//        jTextField3.setText("");
//        jTextField5.setText("HH:mm:ss");
//        jTextField7.setText("HH:mm:ss");
//        jDateChooser1.setDate(null);
//        jComboBox1.setSelectedIndex(-1);
//        jComboBox2.setSelectedIndex(0);
//        jComboBox3.setSelectedIndex(0);
//        jComboBox4.setSelectedIndex(-1);
//        jTextField1.requestFocus();
//        PreparedStatement ps;
//        ResultSet rs;
//        if (DBConnect.open()) {
//            try {
//                ps = DBConnect.cnn.prepareStatement("SELECT ma_lop_mo_DK, thoi_gian_bat_dau, thoi_gian_ket_thuc, thu, tuan_hoc, loai_lop, id_mon_hoc_DK, nhom, phong_hoc, hoc_ki, so_luong_da_dang_ki, so_luong_max_DK, date_to_exist FROM danh_sach_lop_mo_DK");
//                rs = ps.executeQuery();
//                while (jTable1.getRowCount() > 0) {
//                    ((DefaultTableModel) jTable1.getModel()).removeRow(0);
//                }
//                int col = rs.getMetaData().getColumnCount();
//                while (rs.next()) {
//                    Object[] rows = new Object[col];
//                    for (int i = 1; i <= col; i++) {
//                        rows[i - 1] = rs.getObject(i);
//                    }
//                    ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow() - 1, rows);
//                }
//                rs.close();
//            } catch (SQLException e) {
//                Logger.getLogger(Tuition.class.getName()).log(Level.SEVERE, null, e);
//            }
//        }
//    }

    private void reSet1() throws SQLException {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField3.setText("");
        jTextField5.setText("HH:mm:ss");
        jTextField7.setText("HH:mm:ss");
        jDateChooser1.setDate(null);
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(-1);
        jTextField1.requestFocus();
        CheckCreateCourses checkCreateCourses = new CheckCreateCourses();
        ResultSet rs1 = checkCreateCourses.reSet1();
        while(rs1.next()){
            jComboBox4.addItem(rs1.getString(1));
        }
        
        }
        private void reSet2() throws SQLException {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField3.setText("");
        jTextField5.setText("HH:mm:ss");
        jTextField7.setText("HH:mm:ss");
        jDateChooser1.setDate(null);
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(-1);
        jTextField1.requestFocus();
        CheckCreateCourses checkCreateCourses = new CheckCreateCourses();
        ResultSet rs2 = checkCreateCourses.reSet2();
        while(rs2.next()){
            jComboBox1.addItem(rs2.getString(1));
        }
        
        }
        
        private void reSet3() throws SQLException {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField3.setText("");
        jTextField5.setText("HH:mm:ss");
        jTextField7.setText("HH:mm:ss");
        jDateChooser1.setDate(null);
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(-1);
        jTextField1.requestFocus();
        CheckCreateCourses checkCreateCourses = new CheckCreateCourses();
        ResultSet rs = checkCreateCourses.reSet3();
        while (jTable1.getRowCount() > 0) {
           ((DefaultTableModel) jTable1.getModel()).removeRow(0);
        }
        int col = rs.getMetaData().getColumnCount();
        while (rs.next()) {
            Object[] rows = new Object[col];
            for (int i = 1; i <= col; i++) {
            rows[i - 1] = rs.getObject(i);
            }
            ((DefaultTableModel) jTable1.getModel()).insertRow(rs.getRow() - 1, rows);
        }
    }
}

//    private boolean checkinfo() {
//        Check c = new Check();
//        String string = jTextField4.getText();
//        int maxDK = Integer.parseInt(string);
//        java.util.Date hanDK = jDateChooser1.getDate();
//        java.sql.Date sqlDate = new java.sql.Date(hanDK.getTime());
//        String checkNull = "";
//        if (!c.checkIDCourses(jTextField1.getText()) || !c.check(jTextField1.getText())) {
//            JOptionPane.showMessageDialog(this.main, "Mã lớp phải có độ dài 6 kí tự và chỉ chứa các kí tự [^0-9]!", "Hãy nhập lại", JOptionPane.WARNING_MESSAGE);
//            jTextField1.setText("");
//            jTextField1.requestFocus();
//            return false;
//        } else if (!c.check(jTextField2.getText())) {
//            JOptionPane.showMessageDialog(this.main, "Các trường dữ liệu không được trống!", "Hãy nhập lại", JOptionPane.WARNING_MESSAGE);
//            jTextField2.requestFocus();
//            return false;
//        } else if (!c.check(jTextField3.getText())) {
//            JOptionPane.showMessageDialog(this.main, "Các trường dữ liệu không được trống!", "Hãy nhập lại", JOptionPane.WARNING_MESSAGE);
//            jTextField3.requestFocus();
//            return false;
//        } else if (!c.check(jTextField6.getText())) {
//            JOptionPane.showMessageDialog(this.main, "Các trường dữ liệu không được trống!", "Hãy nhập lại", JOptionPane.WARNING_MESSAGE);
//            jTextField6.requestFocus();
//            return false;
//        } else if (maxDK <= 0 || maxDK > 200 || string == null) {
//            JOptionPane.showMessageDialog(this.main, "Số lượng sinh viên một lớp không hợp lệ!", "Hãy nhập lại", JOptionPane.WARNING_MESSAGE);
//            jTextField4.requestFocus();
//            return false;
//        }
//
//        return true;
//    }

//    private void getDataFromSearch() {
//        if (DBConnect.open()) {
//            PreparedStatement psSearch = null;
//            ResultSet rsSearch = null;
//            String s = (String) jComboBox4.getSelectedItem();
//            if (DBConnect.open()) {
//                try {
//                    psSearch = DBConnect.cnn.prepareStatement("SELECT ma_lop_mo_DK, thoi_gian_bat_dau, thoi_gian_ket_thuc, thu, tuan_hoc, loai_lop, id_mon_hoc_DK, nhom, phong_hoc, hoc_ki, so_luong_da_dang_ki, so_luong_max_DK, date_to_exist FROM danh_sach_lop_mo_DK WHERE nhom=?");
//                    psSearch.setString(1, s);
//                    rsSearch = psSearch.executeQuery();
//                    while (jTable1.getRowCount() > 0) {
//                        ((DefaultTableModel) jTable1.getModel()).removeRow(0);
//                    }
//                    int col = rsSearch.getMetaData().getColumnCount();
//                    while (rsSearch.next()) {
//                        Object[] rows = new Object[col];
//                        for (int i = 1; i <= col; i++) {
//                            rows[i - 1] = rsSearch.getObject(i);
//                        }
//                        ((DefaultTableModel) jTable1.getModel()).insertRow(rsSearch.getRow() - 1, rows);
//                    }
//                } catch (SQLException ex) {
//                    Logger.getLogger(CreateStudentInfomation.class.getName()).log(Level.SEVERE, null, ex);
//                } finally {
//                    DBConnect.close(psSearch, rsSearch);
//                }
//            }
//        }
//    }

