/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hust.soict.ui.admin;

import edu.hust.soict.ui.AboutUs;
import edu.hust.soict.ui.AdminLogin;
import edu.hust.soict.ui.MainLogin;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 * Main Frame of admin.
 *
 * @author quangnd
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        //  this.setLocationRelativeTo(null)
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpContent = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmHeThong = new javax.swing.JMenu();
        jmiLogOff = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jmiExit = new javax.swing.JMenuItem();
        jmTacVu = new javax.swing.JMenu();
        jmiAddUser = new javax.swing.JMenuItem();
        jmiNhapSV = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiNhapGV = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiNhapDiem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiNhapLop = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmiMonHoc = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmiNhapKhoa = new javax.swing.JMenuItem();
        jmTimKiem = new javax.swing.JMenu();
        jmHoTro = new javax.swing.JMenu();
        jmHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ SINH VIÊN - ĐẠI HỌC BÁCH KHOA HÀ NỘI");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/iconbkhn.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(7, 1));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/user (1).png"))); // NOI18N
        jLabel2.setText("Quản lý tài khoản");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2);

        jLabel8.setBackground(new java.awt.Color(204, 0, 0));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/scores.png"))); // NOI18N
        jLabel8.setText(" Kết quả học tập");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(jLabel8);

        jLabel5.setBackground(new java.awt.Color(204, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/settings.png"))); // NOI18N
        jLabel5.setText("Quản lý ĐK lớp học");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5);

        jLabel9.setBackground(new java.awt.Color(204, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/file.png"))); // NOI18N
        jLabel9.setText(" Danh sách SVĐK");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9);

        jLabel4.setBackground(new java.awt.Color(204, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/mortarboard (1).png"))); // NOI18N
        jLabel4.setText("Quản lý sinh viên");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4);

        jLabel6.setBackground(new java.awt.Color(204, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/content-management (1).png"))); // NOI18N
        jLabel6.setText("Thông tin lớp ĐK");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6);

        jLabel7.setBackground(new java.awt.Color(204, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/budget.png"))); // NOI18N
        jLabel7.setText("Học phí sinh viên");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel7);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hanoi University of Science and Technology");

        jtpContent.setBackground(new java.awt.Color(255, 255, 255));
        jtpContent.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        jtpContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.white));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/2016321 BK2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 843, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 472, Short.MAX_VALUE)
        );

        jtpContent.addTab("Main", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpContent, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpContent)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 631, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jmHeThong.setForeground(new java.awt.Color(255, 0, 0));
        jmHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/house (1).png"))); // NOI18N
        jmHeThong.setText("System");

        jmiLogOff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jmiLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/Logoff.png"))); // NOI18N
        jmiLogOff.setText("Log Off");
        jmiLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOffActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiLogOff);
        jmHeThong.add(jSeparator7);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/logout.png"))); // NOI18N
        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiExit);

        jMenuBar1.add(jmHeThong);

        jmTacVu.setForeground(new java.awt.Color(255, 0, 0));
        jmTacVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/notes.png"))); // NOI18N
        jmTacVu.setText("Task");

        jmiAddUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jmiAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/plusitem.png"))); // NOI18N
        jmiAddUser.setText("Tạo Mới Người Dùng");
        jmiAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddUserActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiAddUser);

        jmiNhapSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapSV.setText("Nhập Sinh Viên");
        jmiNhapSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapSVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapSV);
        jmTacVu.add(jSeparator2);

        jmiNhapGV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapGV.setText("Nhập Giảng Viên");
        jmiNhapGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapGVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapGV);
        jmTacVu.add(jSeparator3);

        jmiNhapDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapDiem.setText("Nhập Điểm ");
        jmiNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapDiemActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapDiem);
        jmTacVu.add(jSeparator4);

        jmiNhapLop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapLop.setText("Nhập Lớp");
        jmiNhapLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapLopActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapLop);
        jmTacVu.add(jSeparator5);

        jmiMonHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jmiMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiMonHoc.setText("Nhập Môn Học");
        jmiMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMonHocActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiMonHoc);
        jmTacVu.add(jSeparator6);

        jmiNhapKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapKhoa.setText("Nhập Khoa");
        jmiNhapKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapKhoaActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapKhoa);

        jMenuBar1.add(jmTacVu);

        jmTimKiem.setForeground(new java.awt.Color(255, 0, 0));
        jmTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/seo.png"))); // NOI18N
        jmTimKiem.setText("Search");
        jmTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmTimKiemMouseClicked(evt);
            }
        });
        jmTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTimKiemActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmTimKiem);

        jmHoTro.setForeground(new java.awt.Color(255, 0, 0));
        jmHoTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/paper-plane.png"))); // NOI18N
        jmHoTro.setText("About Us");
        jmHoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmHoTroMouseClicked(evt);
            }
        });
        jmHoTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHoTroActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmHoTro);

        jmHelp.setForeground(new java.awt.Color(255, 0, 0));
        jmHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/mail (1).png"))); // NOI18N
        jmHelp.setText("Help");
        jmHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmHelpMouseClicked(evt);
            }
        });
        jmHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHelpActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogOffActionPerformed
        // TODO add your handling code here:
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_jmiLogOffActionPerformed

    private void jmiNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapDiemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jmiNhapDiemActionPerformed

    private void jmiNhapGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapGVActionPerformed
        // TODO add your handling code here:
        // frmGiaoVien giaoVien = new frmGiaoVien();
        //jtpContent.removeAll();
        // jtpContent.add("Thông Tin Giảng Viên", giaoVien);

    }//GEN-LAST:event_jmiNhapGVActionPerformed

    private void jmiNhapKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapKhoaActionPerformed
        // TODO add your handling code here:
        // frmKhoa khoa = new frmKhoa();
        //  jtpContent.removeAll();
        // jtpContent.add("Thông Tin Khoa Viện", khoa);
    }//GEN-LAST:event_jmiNhapKhoaActionPerformed

    private void jmiNhapSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapSVActionPerformed
        // TODO add your handling code here:
        //  frmSinhVien sinhVien = new frmSinhVien();
        // jtpContent.removeAll();
        //  jtpContent.add("Thông Tin Sinh Viên", sinhVien);

    }//GEN-LAST:event_jmiNhapSVActionPerformed

    private void jmiNhapLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapLopActionPerformed
        // TODO add your handling code here:
        //frmLopHoc lophoc = new frmLopHoc();
        //jtpContent.removeAll();
        // jtpContent.add("Thông Tin Lớp Học", lophoc);
    }//GEN-LAST:event_jmiNhapLopActionPerformed

    private void jmiMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMonHocActionPerformed
        // TODO add your handling code here:
        // frmMonHoc monhoc = new frmMonHoc();
        // jtpContent.removeAll();
        //  jtpContent.add("Thông Tin Môn Học", monhoc);
    }//GEN-LAST:event_jmiMonHocActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
        MainLogin mainLogin = new MainLogin();
        mainLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmHoTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmHoTroMouseClicked
        // TODO add your handling code here:
        // AboutMe aboutMe = new AboutMe();
        // aboutMe.setVisible(true);
        AboutUs aboutUs = new AboutUs();
        aboutUs.setVisible(true);
    }//GEN-LAST:event_jmHoTroMouseClicked

    private void jmHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmHelpMouseClicked
        // TODO add your handling code here:
//        String fileName = "D:\\New folder\\QuanLySinhVien\\src\\Help\\HelpTutorial.chm";
//        String[] commands = {"cmd", "/c", fileName};
//        try {
//            Runtime.getRuntime().exec(commands);
//            //Runtime.getRuntime().exec("D:\New folder\QuanLySinhVien\src\Help\HelpTutorial.chm");
//        } catch (IOException ex) {
//        }
    }//GEN-LAST:event_jmHelpMouseClicked

    private void jmTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmTimKiemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jmTimKiemMouseClicked

    private void jmTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTimKiemActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jmTimKiemActionPerformed

    private void jmiAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddUserActionPerformed
        try {
            // TODO add your handling code here:
            ManagerUser addUser = new ManagerUser();
            jtpContent.removeAll();
            jtpContent.add("MANAGER USERS", addUser);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiAddUserActionPerformed

    private void jmHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmHelpActionPerformed

    private void jmHoTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHoTroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmHoTroActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            ManagerUser managerUser = new ManagerUser();
            jtpContent.removeAll();
            jtpContent.add("MANAGER USERS", managerUser);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Tuition tuition = new Tuition();
        tuition.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        CoursesInfromation coursesInfromation = new CoursesInfromation();
        coursesInfromation.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        ExportDataForm exportDataForm = new ExportDataForm();
        exportDataForm.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        try {
            // TODO add your handling code here:
//        ClassRegister classRegister = new ClassRegister();
//        classRegister.setVisible(true);
          CreateCourses createCourses = new CreateCourses();
          jtpContent.removeAll();
          jtpContent.add("MANAGER COURSES", createCourses);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        CreateStudentInfomation infomation = new CreateStudentInfomation();
        jtpContent.removeAll();
        jtpContent.add("MANAGER STUDENTS", infomation);
    }//GEN-LAST:event_jLabel4MouseClicked
    void setColor(JLabel jLabel) {
        jLabel.setBackground(new Color(85, 65, 118));
    }

    void reSetColor(JLabel jLabel) {
        jLabel.setBackground(new Color(255, 255, 255));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenu jmHeThong;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenu jmHoTro;
    private javax.swing.JMenu jmTacVu;
    private javax.swing.JMenu jmTimKiem;
    private javax.swing.JMenuItem jmiAddUser;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLogOff;
    private javax.swing.JMenuItem jmiMonHoc;
    private javax.swing.JMenuItem jmiNhapDiem;
    private javax.swing.JMenuItem jmiNhapGV;
    private javax.swing.JMenuItem jmiNhapKhoa;
    private javax.swing.JMenuItem jmiNhapLop;
    private javax.swing.JMenuItem jmiNhapSV;
    public javax.swing.JTabbedPane jtpContent;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/edu/hust/soict/resources/HUST.png")));
    }

}
