/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hust.soict.ui;

import edu.hust.soict.dao.DBConnect;
import edu.hust.soict.logic.CheckLogin;
import edu.hust.soict.ui.student.ChangePassword;
import edu.hust.soict.ui.student.MainStudent;
import edu.hust.soict.ui.student.Schedule;
import edu.hust.soict.ui.student.StudentRegisterCourses;
import edu.hust.soict.ui.student.StudentInfomation;
import edu.hust.soict.logic.PasswordUtils;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 * Student form login.
 *
 * @author quangnd
 */
public class StudentsLogin extends javax.swing.JFrame {

    ResultSet rs, rs1;
    PreparedStatement ps, ps1;

    /**
     * Creates new form frmLogin
     */
    public StudentsLogin() {
        initComponents();
        jProgressBar1.setVisible(false);
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        jpPassword = new javax.swing.JPasswordField();
        jbLogin = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Student Login");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/HUST.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FORM STUDENTS LOGIN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Username:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password:");

        jtfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsernameActionPerformed(evt);
            }
        });
        jtfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfUsernameKeyReleased(evt);
            }
        });

        jpPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpPasswordKeyReleased(evt);
            }
        });

        jbLogin.setBackground(new java.awt.Color(204, 0, 0));
        jbLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbLogin.setForeground(new java.awt.Color(255, 255, 255));
        jbLogin.setText("Login");
        jbLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoginActionPerformed(evt);
            }
        });
        jbLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbLoginKeyReleased(evt);
            }
        });

        jbCancel.setBackground(new java.awt.Color(204, 0, 0));
        jbCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCancel.setForeground(new java.awt.Color(255, 255, 255));
        jbCancel.setText("Exit");
        jbCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jbCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbCancelKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(15, 15, 15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfUsername)
                                    .addComponent(jpPassword))))))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancel)
                    .addComponent(jbLogin))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoginActionPerformed
        try {
            // TODO add your handling code here:
            String user = jtfUsername.getText();
            String pass = jpPassword.getText();
            String role = "student";
            CheckLogin check = new CheckLogin();
            if (check.checkInputNullAccount(user, pass) == true) {
                JOptionPane.showMessageDialog(null, "Tên đăng nhập và mật khẩu không được trống!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }else if(check.checkStudentLogin(user, pass, role) == true){
                this.dispose();
                JOptionPane.showMessageDialog(StudentsLogin.this, "Bạn đã đăng nhập thành công!");
            }else{
            JOptionPane.showMessageDialog(StudentsLogin.this, "Đã có lỗi xảy ra vui lòng đăng nhập lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentsLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbLoginActionPerformed

    private void jtfUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfUsernameKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jpPassword.requestFocus();

        }
    }//GEN-LAST:event_jtfUsernameKeyReleased

    private void jpPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpPasswordKeyReleased
        // TODO add your handling code here:
//        if (evt.getKeyCode() == evt.VK_ENTER) {
//            send();
//        }
    }//GEN-LAST:event_jpPasswordKeyReleased

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        // TODO add your handling code here:
        MainLogin login = new MainLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbLoginKeyReleased
        // TODO add your handling code here:
//        if (evt.getKeyCode() == evt.VK_ENTER) {
//            send();
//        }
    }//GEN-LAST:event_jbLoginKeyReleased

    private void jbCancelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCancelKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbCancelKeyReleased

    private void jtfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsernameActionPerformed


    /**
     *
     */
    public class BackgroundWorker extends SwingWorker<Void, Void> {

        /**
         *
         */
        public BackgroundWorker() {
            addPropertyChangeListener((PropertyChangeEvent evt) -> {
                jProgressBar1.setValue(getProgress());
            });
        }

        @Override
        protected void done() {
            if (jProgressBar1.getValue() == 100 || jProgressBar1.getValue() == 0) {
                JOptionPane.showMessageDialog(StudentsLogin.this,
                        "Đã có lỗi xảy ra, vui lòng đăng nhập lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(StudentsLogin.this,
                        "Bạn đã đăng nhập thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }

            //jbLogin.setEnabled(true);
        }

        @Override
        protected Void doInBackground() throws Exception {

            try {
                String strnull = "";
                String user = jtfUsername.getText();
                String pass = jpPassword.getText();
                String role = "student";
                if (user.equals(strnull) || pass.equals(strnull)) {
                    JOptionPane.showMessageDialog(StudentsLogin.this,
                            "Tên đăng nhập và mật khẩu không được trống!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    resetForm();
                } else if (DBConnect.open()) {
                    try {
                        //ps = DBConnect.cnn.prepareCall("{call validation_login()}");
                        ps = DBConnect.cnn.prepareCall("SELECT dang_nhap.user_name, thong_tin_sinh_vien.ten_sinh_vien, dang_nhap.password, dang_nhap.is_admin, thong_tin_sinh_vien.email, thong_tin_sinh_vien.ngay_sinh, thong_tin_sinh_vien.lop_hoc, thong_tin_sinh_vien.chuong_trinh_DT, thong_tin_sinh_vien.he_hoc, thong_tin_sinh_vien.trang_thai FROM dang_nhap \n"
                                + "INNER JOIN thong_tin_sinh_vien ON dang_nhap.user_name = thong_tin_sinh_vien.id_sinh_vien WHERE dang_nhap.user_name =" + user);
                        //ps1 = DBConnect.cnn.prepareStatement("SELECT user_name FROM dang_nhap");
                        rs = ps.executeQuery();
                        rs.last();
                        int count = rs.getRow();
                        rs.beforeFirst();
                        while (rs.next()) {
                            int i = rs.getRow();
                            String username = rs.getString(1);
                            String getPasswordDatabase = rs.getString(3);
                            String is_admin = rs.getString(4);
                            String name = rs.getString(2);
                            String ngay_sinh = rs.getString(6);
                            String lop_hoc = rs.getString(7);
                            String chuong_trinh_DT = rs.getString(8);
                            String he_hoc = rs.getString(9);
                            String email = rs.getString(5);
                            String trang_thai = rs.getString(10);
                            boolean encryptedPassword = PasswordUtils.checkPassword(pass, getPasswordDatabase);
                            if ((user.equals(username)) && (encryptedPassword == true) && (role.equals(is_admin))) {
                                MainStudent mainstudent = new MainStudent(username, name, ngay_sinh, lop_hoc, chuong_trinh_DT, trang_thai, email, he_hoc);
                                ChangePassword changePassword = new ChangePassword(username);
                                StudentInfomation thongtinsv = new StudentInfomation(username, name, ngay_sinh, lop_hoc, chuong_trinh_DT, trang_thai, email, he_hoc);
                                StudentRegisterCourses search = new StudentRegisterCourses(username);
                                Schedule schedule = new Schedule(username);
                                mainstudent.setVisible(true);
                                thongtinsv.setVisible(true);
                                search.setVisible(true);
                                changePassword.setVisible(true);
                                //changePassword.setVisible(true);
                                setProgress((int) ((i * 100) / count));
                                Thread.sleep(10);
                                dispose();
                                break;
                            }
                            setProgress((int) ((i * 100) / count));
                            Thread.sleep(10);
                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(StudentsLogin.class
                                .getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } catch (HeadlessException | InterruptedException e) {
                // TODO Auto-generated catch block
            }

            return null;
        }

    }

    /**
     * Reset username, password to null.
     */
    public void resetForm() {
        jtfUsername.setText("");
        jpPassword.setText("");
        jtfUsername.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new StudentsLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbLogin;
    public javax.swing.JPasswordField jpPassword;
    public javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables

    /**
     * Set icon tab of application.
     */
    private void setIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/edu/hust/soict/resources/HUST.png")));
    }
}
