/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hust.soict.ui.student;

import edu.hust.soict.ui.AboutUs;
import edu.hust.soict.ui.admin.*;
import edu.hust.soict.ui.MainLogin;
import edu.hust.soict.ui.StudentsLogin;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Class MainStudent: Home view of application.
 *
 * @author quangnd
 */
public class MainStudent extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    String userLogin;
    String name;
    String ngaySinh;
    String lopHoc;
    String chuongTrinhDT;
    String trangThai;
    String email;
    String heHoc;
    Double tuiTion;
    //  PreparedStatement ps = null;
    // ResultSet rs = null;

    /**
     *
     */
    public MainStudent() {

        initComponents();
        //  this.setLocationRelativeTo(null);
        setIcon();
    }

    /**
     *
     * @param tuition
     */
    public MainStudent(Double tuition) {

        initComponents();
        //  this.setLocationRelativeTo(null);
        this.tuiTion = tuition;
        setIcon();
    }

//     public MainStudent(Float tuition) {
//
//        initComponents();
//        //  this.setLocationRelativeTo(null);
//        this.tuiTion = tuition;
//        setIcon();
//    }
    /**
     *
     *
     * @param username
     * @param name
     * @param ngay_sinh
     * @param lop_hoc
     * @param chuong_trinh_DT
     * @param trang_thai
     * @param email
     * @param he_hoc
     * @throws SQLException
     */
    public MainStudent(String username, String name, String ngay_sinh, String lop_hoc, String chuong_trinh_DT, String trang_thai, String email, String he_hoc) throws SQLException {

        this.userLogin = username;
        this.name = name;
        this.chuongTrinhDT = chuong_trinh_DT;
        this.lopHoc = lop_hoc;
        this.trangThai = trang_thai;
        this.email = email;
        this.heHoc = he_hoc;
        this.ngaySinh = ngay_sinh;
//        this.tuiTion = tuition;
        initComponents();
        setIcon();
        //String getValue = jLabel2.getText();
        //jLabel2.setText(getValue + ":" + username);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbInputStudent = new javax.swing.JButton();
        jbInputTeacher = new javax.swing.JButton();
        jbClass = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jbInputTeacher1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtpContent = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmHeThong = new javax.swing.JMenu();
        jmiLogOff = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jmiExit = new javax.swing.JMenuItem();
        jmTacVu = new javax.swing.JMenu();
        jmiAddUser = new javax.swing.JMenuItem();
        jmiNhapSV = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiNhapGV = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiNhapDiem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmiNhapLop = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmiMonHoc = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jmiNhapKhoa = new javax.swing.JMenuItem();
        jmTimKiem = new javax.swing.JMenu();
        jmHoTro = new javax.swing.JMenu();
        jmHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG THÔNG TIN SINH VIÊN - ĐẠI HỌC BÁCH KHOA HÀ NỘI");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/iconbkhn.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));

        jbInputStudent.setBackground(new java.awt.Color(204, 0, 0));
        jbInputStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbInputStudent.setForeground(new java.awt.Color(255, 255, 255));
        jbInputStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/information.png"))); // NOI18N
        jbInputStudent.setText("Thông tin SV");
        jbInputStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbInputStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputStudentActionPerformed(evt);
            }
        });

        jbInputTeacher.setBackground(new java.awt.Color(204, 0, 0));
        jbInputTeacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbInputTeacher.setForeground(new java.awt.Color(255, 255, 255));
        jbInputTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/clipboard.png"))); // NOI18N
        jbInputTeacher.setText("Đăng kí học tập");
        jbInputTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbInputTeacher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputTeacherActionPerformed(evt);
            }
        });

        jbClass.setBackground(new java.awt.Color(204, 0, 0));
        jbClass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbClass.setForeground(new java.awt.Color(255, 255, 255));
        jbClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/online-education.png"))); // NOI18N
        jbClass.setText("Lớp mở ĐK");
        jbClass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbClass.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClassActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/shield.png"))); // NOI18N
        jButton6.setText("Tra cứu ");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/notes.png"))); // NOI18N
        jButton7.setText("Học phí SV");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jbInputTeacher1.setBackground(new java.awt.Color(204, 0, 0));
        jbInputTeacher1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbInputTeacher1.setForeground(new java.awt.Color(255, 255, 255));
        jbInputTeacher1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/ebook.png"))); // NOI18N
        jbInputTeacher1.setText("Môn học");
        jbInputTeacher1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbInputTeacher1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbInputTeacher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInputTeacher1ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/calendar.png"))); // NOI18N
        jButton8.setText("Thời KB *");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbInputStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbInputTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jbInputTeacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jbInputStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbInputTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbInputTeacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hanoi University of Science and Technology ");

        jtpContent.setBackground(new java.awt.Color(255, 255, 255));
        jtpContent.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.white));
        jtpContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.white));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/2016321 BK2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 795, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 459, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jtpContent.addTab("Main", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpContent)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpContent))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 811, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jmHeThong.setForeground(new java.awt.Color(204, 0, 0));
        jmHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/house (1).png"))); // NOI18N
        jmHeThong.setText("System");
        jmHeThong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jmiLogOff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jmiLogOff.setForeground(new java.awt.Color(0, 0, 0));
        jmiLogOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/Logoff.png"))); // NOI18N
        jmiLogOff.setText("Log Out");
        jmiLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogOffActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiLogOff);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/bar-chart-reload.png"))); // NOI18N
        jMenuItem1.setText("Change Password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmHeThong.add(jMenuItem1);
        jmHeThong.add(jSeparator7);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jmiExit.setForeground(new java.awt.Color(0, 0, 0));
        jmiExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/logout.png"))); // NOI18N
        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmHeThong.add(jmiExit);

        jMenuBar1.add(jmHeThong);

        jmTacVu.setForeground(new java.awt.Color(204, 0, 0));
        jmTacVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/notes.png"))); // NOI18N
        jmTacVu.setText("Task");
        jmTacVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jmiAddUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jmiAddUser.setForeground(new java.awt.Color(0, 0, 0));
        jmiAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/plusitem.png"))); // NOI18N
        jmiAddUser.setText("Tạo Mới Người Dùng");
        jmiAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddUserActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiAddUser);

        jmiNhapSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapSV.setForeground(new java.awt.Color(0, 0, 0));
        jmiNhapSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapSV.setText("Nhập Sinh Viên");
        jmiNhapSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapSVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapSV);
        jmTacVu.add(jSeparator2);

        jmiNhapGV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapGV.setForeground(new java.awt.Color(0, 0, 0));
        jmiNhapGV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapGV.setText("Nhập Giảng Viên");
        jmiNhapGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapGVActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapGV);
        jmTacVu.add(jSeparator3);

        jmiNhapDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapDiem.setForeground(new java.awt.Color(0, 0, 0));
        jmiNhapDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapDiem.setText("Nhập Điểm ");
        jmiNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapDiemActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapDiem);
        jmTacVu.add(jSeparator4);

        jmiNhapLop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapLop.setForeground(new java.awt.Color(0, 0, 0));
        jmiNhapLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapLop.setText("Nhập Lớp");
        jmiNhapLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapLopActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapLop);
        jmTacVu.add(jSeparator5);

        jmiMonHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jmiMonHoc.setForeground(new java.awt.Color(0, 0, 0));
        jmiMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiMonHoc.setText("Nhập Môn Học");
        jmiMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMonHocActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiMonHoc);
        jmTacVu.add(jSeparator6);

        jmiNhapKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        jmiNhapKhoa.setForeground(new java.awt.Color(0, 0, 0));
        jmiNhapKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/new.png"))); // NOI18N
        jmiNhapKhoa.setText("Nhập Khoa");
        jmiNhapKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNhapKhoaActionPerformed(evt);
            }
        });
        jmTacVu.add(jmiNhapKhoa);

        jMenuBar1.add(jmTacVu);

        jmTimKiem.setForeground(new java.awt.Color(204, 0, 0));
        jmTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/seo.png"))); // NOI18N
        jmTimKiem.setText("Search");
        jmTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmTimKiemMouseClicked(evt);
            }
        });
        jmTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTimKiemActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmTimKiem);

        jmHoTro.setForeground(new java.awt.Color(204, 0, 0));
        jmHoTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/paper-plane.png"))); // NOI18N
        jmHoTro.setText("About Us");
        jmHoTro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmHoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmHoTroMouseClicked(evt);
            }
        });
        jmHoTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHoTroActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmHoTro);

        jmHelp.setForeground(new java.awt.Color(204, 0, 0));
        jmHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/mail (1).png"))); // NOI18N
        jmHelp.setText("Help");
        jmHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmHelpMouseClicked(evt);
            }
        });
        jmHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmHelpActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogOffActionPerformed
        // TODO add your handling code here:
        StudentsLogin login = new StudentsLogin();
        login.setVisible(true);
        dispose();

    }//GEN-LAST:event_jmiLogOffActionPerformed

    private void jmiNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapDiemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jmiNhapDiemActionPerformed
    /**
     *
     * When clicked Button "Thông tin SV" get new Frame ThongTinSV with
     * information of Student logged in.
     *
     * @param action_event
     */
    private void jbInputStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputStudentActionPerformed
        // TODO add your handling code here:
        StudentInfomation thongTinSV = new StudentInfomation(userLogin, name, ngaySinh, chuongTrinhDT, lopHoc, trangThai, email, heHoc);
        jtpContent.removeAll();
        jtpContent.add("STUDENT INFORMATION", thongTinSV);

    }//GEN-LAST:event_jbInputStudentActionPerformed

    private void jmiNhapGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapGVActionPerformed
        // TODO add your handling code here:
        // frmGiaoVien giaoVien = new frmGiaoVien();
        //jtpContent.removeAll();
        // jtpContent.add("Thông Tin Giảng Viên", giaoVien);

    }//GEN-LAST:event_jmiNhapGVActionPerformed

    private void jmiNhapKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapKhoaActionPerformed
        // TODO add your handling code here:
        // frmKhoa khoa = new frmKhoa();
        //  jtpContent.removeAll();
        // jtpContent.add("Thông Tin Khoa Viện", khoa);
    }//GEN-LAST:event_jmiNhapKhoaActionPerformed

    private void jmiNhapSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapSVActionPerformed
        // TODO add your handling code here:
        //  frmSinhVien sinhVien = new frmSinhVien();
        // jtpContent.removeAll();
        //  jtpContent.add("Thông Tin Sinh Viên", sinhVien);
//        ChangePassword changePassword = new ChangePassword(this, rootPaneCheckingEnabled);
//        changePassword.setVisible(true);

    }//GEN-LAST:event_jmiNhapSVActionPerformed

    private void jbInputTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputTeacherActionPerformed
        try {
            // TODO add your handling code here:
            if (trangThai.equals("Đình chỉ học tập")) {
                JOptionPane.showMessageDialog(this, "Bạn không thể đăng kí học tập kì này"+"\n" + "Do trong thời gian đình chỉ học tập!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            } else {
                StudentRegisterCourses registerCourses = new StudentRegisterCourses(userLogin);
                //search.jTabbedPane1.setSelectedIndex(1);
                jtpContent.removeAll();
                jtpContent.add("COURSES INFOMATION", registerCourses);
            }

        } catch (SQLException ex) {
            Logger.getLogger(MainStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbInputTeacherActionPerformed

    private void jbClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClassActionPerformed
        // TODO add your handling code here:
        CoursesInfromation coursesInfromation = new CoursesInfromation();
        coursesInfromation.setVisible(true);
    }//GEN-LAST:event_jbClassActionPerformed
    /**
     * Get form Search information student, register course.
     *
     * @param evt
     *
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
                SearchInfoStudent search = new SearchInfoStudent(userLogin);
                jtpContent.removeAll();
                jtpContent.add("STUDENT INFORMATION SEARCH", search);
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(MainStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jmiNhapLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNhapLopActionPerformed
        // TODO add your handling code here:
        //frmLopHoc lophoc = new frmLopHoc();
        //jtpContent.removeAll();
        // jtpContent.add("Thông Tin Lớp Học", lophoc);
    }//GEN-LAST:event_jmiNhapLopActionPerformed

    private void jmiMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMonHocActionPerformed
        // TODO add your handling code here:
        // frmMonHoc monhoc = new frmMonHoc();
        // jtpContent.removeAll();
        //  jtpContent.add("Thông Tin Môn Học", monhoc);
    }//GEN-LAST:event_jmiMonHocActionPerformed

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        // TODO add your handling code here:
        MainLogin mainLogin = new MainLogin();
        mainLogin.setVisible(true);
        dispose();

    }//GEN-LAST:event_jmiExitActionPerformed
    /**
     * Frame AboutUs: get info about Student Information System of HUST.
     *
     * @param evt
     */
    private void jmHoTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmHoTroMouseClicked
        // TODO add your handling code here:
        AboutUs aboutUs = new AboutUs();
        aboutUs.setVisible(true);

    }//GEN-LAST:event_jmHoTroMouseClicked

    private void jmHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmHelpMouseClicked

    }//GEN-LAST:event_jmHelpMouseClicked

    private void jmTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmTimKiemMouseClicked
        try {
            // TODO add your handling code here:
            StudentRegisterCourses search = new StudentRegisterCourses(userLogin);
            jtpContent.removeAll();
            jtpContent.add("STUDENT INFORMATION SEARCH", search);
        } catch (SQLException ex) {
            Logger.getLogger(MainStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmTimKiemMouseClicked

    private void jmTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTimKiemActionPerformed
        // TODO add your handling code here:
        //Search timkiem = new Search();
        // jtpContent.removeAll();
        // jtpContent.add("Tìm Kiếm", timkiem);
    }//GEN-LAST:event_jmTimKiemActionPerformed
    /**
     *
     * @param evt parameter of ActionEvent
     */
    private void jmiAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddUserActionPerformed
        // TODO add your handling code here:
//        FormAddUser addUser = new FormAddUser();
//        jtpContent.removeAll();
//        jtpContent.add("MANAGER USERS", addUser);
    }//GEN-LAST:event_jmiAddUserActionPerformed

    private void jmHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmHelpActionPerformed

    private void jmHoTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmHoTroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmHoTroActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        // TODO add your handling code here:
        TuitionStudent tuitionStudent = null;

        try {
            tuitionStudent = new TuitionStudent(userLogin, name);
        } catch (SQLException ex) {
            Logger.getLogger(MainStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

        tuitionStudent.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jbInputTeacher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInputTeacher1ActionPerformed
        // TODO add your handling code here:
        Subjects subjects = new Subjects();
        subjects.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jbInputTeacher1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Schedule schedule = new Schedule(userLogin);
        schedule.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ChangePassword changePassword = new ChangePassword(userLogin);
        jtpContent.removeAll();
        jtpContent.add("CHANGE PASSWORD", changePassword);
        // changePassword.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new MainStudent().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JButton jbClass;
    private javax.swing.JButton jbInputStudent;
    private javax.swing.JButton jbInputTeacher;
    private javax.swing.JButton jbInputTeacher1;
    private javax.swing.JMenu jmHeThong;
    private javax.swing.JMenu jmHelp;
    private javax.swing.JMenu jmHoTro;
    private javax.swing.JMenu jmTacVu;
    private javax.swing.JMenu jmTimKiem;
    private javax.swing.JMenuItem jmiAddUser;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLogOff;
    private javax.swing.JMenuItem jmiMonHoc;
    private javax.swing.JMenuItem jmiNhapDiem;
    private javax.swing.JMenuItem jmiNhapGV;
    private javax.swing.JMenuItem jmiNhapKhoa;
    private javax.swing.JMenuItem jmiNhapLop;
    private javax.swing.JMenuItem jmiNhapSV;
    private javax.swing.JTabbedPane jtpContent;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/edu/hust/soict/resources/HUST.png")));
    }

}
