/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hust.soict.ui.student;

import edu.hust.soict.dao.StudentDAO;
import edu.hust.soict.objects.Student;
import edu.hust.soict.objects.Class;
import edu.hust.soict.objects.Register;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * Search information students, detail courses and register class.
 *
 * @author BKHN(quangnd)
 */
public class SearchInfoStudent extends javax.swing.JPanel {

    MainStudent mainStudent = new MainStudent();
    private final DefaultTableModel dtmMaSV;
    //private final DefaultTableModel dtmLop;
    //private final DefaultTableModel dtmDetailReg;
    String userlogin;
    PreparedStatement ps, ps1, ps2;
    ResultSet rs, rs1, rs2;
    // ArrayList<BangDiem> listbdiem = null;

    /**
     *
     * @throws SQLException
     */
    public SearchInfoStudent() throws SQLException {
        initComponents();
        dtmMaSV = new DefaultTableModel();
        //dtmLop = new DefaultTableModel();
        //dtmDetailReg = new DefaultTableModel();
        dtmMaSV.addColumn("Mã sinh viên");
        dtmMaSV.addColumn("Họ tên");
        dtmMaSV.addColumn("Lớp");
        dtmMaSV.addColumn("CTĐT");
        dtmMaSV.addColumn("Ngày Sinh");
        dtmMaSV.addColumn("Hệ ĐT");
        dtmMaSV.addColumn("Khóa học");
        dtmMaSV.addColumn("Email");
        dtmMaSV.addColumn("Trạng thái");

        jtbTTSV.setModel(dtmMaSV);
    }

    /**
     * Creates new form Search with data loaded to Table.
     *
     * @param username
     * @throws java.sql.SQLException
     */
    public SearchInfoStudent(String username) throws SQLException {
        initComponents();
        dtmMaSV = new DefaultTableModel();
        //dtmLop = new DefaultTableModel();
        //dtmDetailReg = new DefaultTableModel();
        //TIm kiem sinh vien theo ma lop
        dtmMaSV.addColumn("Mã sinh viên");
        dtmMaSV.addColumn("Họ tên");
        dtmMaSV.addColumn("Lớp");
        dtmMaSV.addColumn("CTĐT");
        dtmMaSV.addColumn("Ngày Sinh");
        dtmMaSV.addColumn("Hệ ĐT");
        dtmMaSV.addColumn("Khóa học");
        dtmMaSV.addColumn("Email");
        dtmMaSV.addColumn("Trạng thái");
        jtbTTSV.setModel(dtmMaSV);
        this.userlogin = username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("quan_ly_sinh_vien?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        thongTinSinhVienQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM ThongTinSinhVien t");
        thongTinSinhVienList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : thongTinSinhVienQuery.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jtfmaSV = new javax.swing.JTextField();
        jbtSearch = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbTTSV = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        setPreferredSize(new java.awt.Dimension(799, 463));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(861, 372));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), java.awt.Color.white));

        jtfmaSV.setToolTipText("Tìm kiếm sinh viên theo mã sinh viên");
        jtfmaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfmaSVActionPerformed(evt);
            }
        });
        jtfmaSV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfmaSVKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfmaSVKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfmaSVKeyReleased(evt);
            }
        });

        jbtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtSearch.setForeground(new java.awt.Color(204, 0, 0));
        jbtSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/hust/soict/resources/bar-chart-reload.png"))); // NOI18N
        jbtSearch.setText("Search");
        jbtSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jtfmaSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSearch)
                .addGap(216, 216, 216))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jtfmaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbtSearch))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        jtbTTSV = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, thongTinSinhVienList, jtbTTSV);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idSinhVien}"));
        columnBinding.setColumnName("Id Sinh Vien");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tenSinhVien}"));
        columnBinding.setColumnName("Ten Sinh Vien");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ngaySinh}"));
        columnBinding.setColumnName("Ngay Sinh");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lopHoc}"));
        columnBinding.setColumnName("Lop Hoc");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${department}"));
        columnBinding.setColumnName("Department");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${khoaHoc}"));
        columnBinding.setColumnName("Khoa Hoc");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${trangThai}"));
        columnBinding.setColumnName("Trang Thai");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${heHoc}"));
        columnBinding.setColumnName("He Hoc");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${chuongtrinhDT}"));
        columnBinding.setColumnName("Chuongtrinh DT");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${donViTinChiHocPhi}"));
        columnBinding.setColumnName("Don Vi Tin Chi Hoc Phi");
        columnBinding.setColumnClass(Float.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jtbTTSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtbTTSVMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtbTTSV);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("STUDENTS", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbTTSVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTTSVMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbTTSVMouseReleased

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
        // TODO add your handling code here:
        timKiemTheoMaSV();
    }//GEN-LAST:event_jbtSearchActionPerformed

    private void jtfmaSVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmaSVKeyReleased
        // TODO add your handling code here:
        //timkiemtheomalop();
    }//GEN-LAST:event_jtfmaSVKeyReleased

    private void jtfmaSVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmaSVKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfmaSVKeyTyped

    private void jtfmaSVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfmaSVKeyPressed
        // TODO add your handling code here:
        //timkiemtheomalop();
    }//GEN-LAST:event_jtfmaSVKeyPressed

    private void jtfmaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfmaSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfmaSVActionPerformed

    /**
     * Search info about student by id.
     * each row is list of Objects 
     * each Object is column of table
     * each column of table is property of student
     */
    public void timKiemTheoMaSV() {
        while (dtmMaSV.getRowCount() > 0) {
            dtmMaSV.removeRow(0);
        }
        String maSV = jtfmaSV.getText();
        StudentDAO stdao = new StudentDAO();
        ArrayList<Student> list = null;
        if (maSV != null && maSV.trim().length() > 0) {
            list = stdao.findByIDStudent(maSV);
            for (Student sv : list) {
                dtmMaSV.addRow(toObjectData(sv));
            }
        } else {
            list = stdao.getAll();
            for (Student sv : list) {
                dtmMaSV.addRow(toObjectData(sv));
            }
        }
    }
    
    private static Object[] toObjectData(Student sv) {
        Object[] objectData = {sv.getId_sinh_vien(), sv.getTen_sinh_vien(), sv.getLop_hoc(),
            sv.getChuong_trinh_DT(), sv.getNgay_sinh(), sv.getHe_hoc(), sv.getKhoa(), sv.getEmail(), sv.getTrang_thai()};
        return objectData;
    }

    /**
     *
     * @param cl
     * @return objects (column of table)
     */
    public static Object[] toOjectClass(Class cl) {
        Object[] objects = {cl.getMa_lop_DK(), cl.getBat_dau(), cl.getKet_thuc(), cl.getThu(), cl.getTuan_hoc(), cl.getLoai_lop(), cl.getMa_mon_hoc(), cl.getNhom(), cl.getPhong_hoc(), cl.getDa_DK(), cl.getMax_DK()};
        return objects;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JTable jtbTTSV;
    private javax.swing.JTextField jtfmaSV;
    private java.util.List<edu.hust.soict.objects.ThongTinSinhVien> thongTinSinhVienList;
    private javax.persistence.Query thongTinSinhVienQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


//    private void getDetailRegister() {
//        while (dtmDetailReg.getRowCount() > 0) {
//            dtmDetailReg.removeRow(0);
//        }
//        String maSV = jTextField1.getText();
//        ClassDAO cldao = new ClassDAO();
//        ArrayList<Register> list = null;
//        //IStudentDAO sinhVienDAO = (IStudentDAO) Class.forName("Student.StudentDAO").newInstance();  -- use Interface
//        list = cldao.findByIDStudentRegister(maSV);
//        for (Register sv : list) {
//            dtmDetailReg.addRow(toObjectStudentRegister(sv));
//        }
//    }

//    private static Object[] toObjectStudentRegister(Register sv) {
//        Object[] objects = {sv.getIdDKLop(), sv.getMaSinhVienDK(), sv.getMaLopDK()};
//        return objects;
//
//    }

//    private void resetForm() {
//        jTextField3.setText("");
//        jTextField2.setText("");
//        jButton1.setEnabled(true);
//        jButton2.setEnabled(false);
//        jTextField2.setEditable(true);
//        //jTextField3.setEditable(true);
//    }

//    private void fetchJLabel4() throws SQLException {
//        if (DBConnect.open()) {
//            ps = DBConnect.cnn.prepareCall("select sum(so_tin_chi)\n"
//                    + "       from mon_hoc, danh_sach_lop_mo_DK, danh_sach_SV_dang_ki_lop\n"
//                    + "       where mon_hoc.id_mon_hoc = danh_sach_lop_mo_DK.id_mon_hoc_DK\n"
//                    + "       and danh_sach_SV_dang_ki_lop.ma_lop_mo_SV_DK = danh_sach_lop_mo_DK.ma_lop_mo_DK \n"
//                    + "       and id_sinh_vien_DK =" + userlogin);
//            rs = ps.executeQuery();
//            if (rs.first()) {
//                Integer integer = rs.getInt(1);
//                String string = "Tổng số TC đã ĐK:";
//                jLabel4.setText(string + integer);
//            }
//
//        }
//    }
//
//    private void fetchListCourses() {
//        if (DBConnect.open()) {
//            try {
//                ps = DBConnect.cnn.prepareStatement("SELECT ma_lop_mo_DK, thoi_gian_bat_dau, thoi_gian_ket_thuc, thu, tuan_hoc, loai_lop, id_mon_hoc_DK, nhom, phong_hoc, so_luong_da_dang_ki, so_luong_max_DK, date_to_exist FROM danh_sach_lop_mo_DK");
//                rs = ps.executeQuery();
//
//                while (jtbLOP.getRowCount() > 0) {
//                    ((DefaultTableModel) jtbLOP.getModel()).removeRow(0);
//                }
//                int col = rs.getMetaData().getColumnCount();
//                while (rs.next()) {
//                    Object[] rows = new Object[col];
//                    for (int i = 1; i <= col; i++) {
//                        rows[i - 1] = rs.getObject(i);
//                    }
//                    ((DefaultTableModel) jtbLOP.getModel()).insertRow(rs.getRow() - 1, rows);
//                }
//                rs.close();
//            } catch (SQLException e) {
//                Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, e);
//            }
//        }
//    }

//    private void fetchRegister() {
//        if (DBConnect.open()) {
//            try {
//                ps = DBConnect.cnn.prepareStatement("SELECT iddanh_sach_SV_dang_ki_lop, id_sinh_vien_DK, ma_lop_mo_SV_DK, danh_sach_lop_mo_DK.id_mon_hoc_DK, mon_hoc.ten_mon_hoc, mon_hoc.so_tin_chi FROM danh_sach_SV_dang_ki_lop, danh_sach_lop_mo_DK, mon_hoc WHERE ma_lop_mo_SV_DK = ma_lop_mo_DK AND mon_hoc.id_mon_hoc=danh_sach_lop_mo_DK.id_mon_hoc_DK AND id_sinh_vien_DK=" + userlogin);
//                rs = ps.executeQuery();
//
//                while (jtbLOP1.getRowCount() > 0) {
//                    ((DefaultTableModel) jtbLOP1.getModel()).removeRow(0);
//                }
//                int col = rs.getMetaData().getColumnCount();
//                while (rs.next()) {
//                    Object[] rows = new Object[col];
//                    for (int i = 1; i <= col; i++) {
//                        rows[i - 1] = rs.getObject(i);
//                    }
//                    ((DefaultTableModel) jtbLOP1.getModel()).insertRow(rs.getRow() - 1, rows);
//                }
//                rs.close();
//            } catch (SQLException e) {
//                Logger.getLogger(Search.class.getName()).log(Level.SEVERE, null, e);
//            }
//        }
//    }

}
